"""Standalone SEEMC imaging transport and provenance package."""

from .geometry import (
    Geometry,
    Plane,
    Scene,
    SOLID_REGION,
    SurfaceHit,
    Slab,
    SuspendedTrapezoidalLine,
    TrapezoidalLine,
    TrapezoidalPrism,
    VACUUM_REGION,
)

from .transport import (
    Electron,
    ElectronRecord,
    Emission,
    HistoryEvent,
    MCConfig,
    SEEMC,
    Sample,
    Secondary,
    TrajectoryHistory,
    TrajectoryResult,
    incident_direction,
    refract_incident_direction,
    simulate_trajectory,
)

from .raster import (
    CHANNEL_DEFINITIONS,
    DEFAULT_LLE_MAX_LOSS_EV,
    DISJOINT_POPULATION_CHANNELS,
    LEGACY_CHANNEL_DEFINITIONS,
    LEGACY_DISJOINT_POPULATION_CHANNELS,
    LEGACY_POPULATION_CHANNELS,
    POPULATION_CHANNELS,
    SE_PARENT_RULES,
    TRANSMISSION_RINGS,
    TransmissionDetector,
    V2_CHANNEL_DEFINITIONS,
    V2_DISJOINT_POPULATION_CHANNELS,
    V2_POPULATION_CHANNELS,
    PopulationClassifier,
    RasterConfig,
    RasterDriver,
    RasterResult,
    sample_beam_reference,
)

from .trajectory import (
    POINT_COLUMNS,
    RasterTrajectoryArchive,
    TRAJECTORY_FORMAT,
)
from .animation import animate_trapezoidal_scan

from .plane_samplers import (
    DEFAULT_INCIDENCE_ANGLES_DEG,
    JMONSEL_ENERGIES_EV,
    PlaneSamplerCase,
    cosine_probability_grid,
    generate_plane_sampler_library,
    run_plane_sampler_case,
)

from .metrology import (
    DEFAULT_CHANNEL_SETS,
    LEGACY_CHANNEL_SETS,
    TRANSMISSION_CHANNEL_SETS,
    TRANSMISSION_DISJOINT_POPULATION_CHANNELS,
    V2_CHANNEL_SETS,
    V062_CHANNEL_SETS,
    V062_DISJOINT_POPULATION_CHANNELS,
    InformationResult,
    PARAMETER_NAMES,
    ProfileFitResult,
    ProfileFitter,
    ProfileObservation,
    TrapezoidModelLibrary,
    TrapezoidSweepConfig,
    TrapezoidSweepDriver,
    compare_channel_information,
)

__all__ = [
    "Electron",
    "ElectronRecord",
    "Emission",
    "Geometry",
    "HistoryEvent",
    "MCConfig",
    "CHANNEL_DEFINITIONS",
    "DEFAULT_CHANNEL_SETS",
    "DEFAULT_LLE_MAX_LOSS_EV",
    "LEGACY_CHANNEL_SETS",
    "SE_PARENT_RULES",
    "TRANSMISSION_RINGS",
    "TransmissionDetector",
    "V2_CHANNEL_DEFINITIONS",
    "TRANSMISSION_CHANNEL_SETS",
    "TRANSMISSION_DISJOINT_POPULATION_CHANNELS",
    "V2_CHANNEL_SETS",
    "V2_DISJOINT_POPULATION_CHANNELS",
    "V2_POPULATION_CHANNELS",
    "V062_CHANNEL_SETS",
    "V062_DISJOINT_POPULATION_CHANNELS",
    "DISJOINT_POPULATION_CHANNELS",
    "LEGACY_CHANNEL_DEFINITIONS",
    "LEGACY_DISJOINT_POPULATION_CHANNELS",
    "LEGACY_POPULATION_CHANNELS",
    "POPULATION_CHANNELS",
    "Plane",
    "InformationResult",
    "PARAMETER_NAMES",
    "PopulationClassifier",
    "ProfileFitResult",
    "ProfileFitter",
    "ProfileObservation",
    "RasterConfig",
    "RasterDriver",
    "RasterResult",
    "RasterTrajectoryArchive",
    "Scene",
    "SEEMC",
    "SOLID_REGION",
    "Sample",
    "Secondary",
    "SurfaceHit",
    "Slab",
    "SuspendedTrapezoidalLine",
    "TrapezoidalLine",
    "TrapezoidalPrism",
    "TrapezoidModelLibrary",
    "TrapezoidSweepConfig",
    "TrapezoidSweepDriver",
    "TrajectoryHistory",
    "TrajectoryResult",
    "TRAJECTORY_FORMAT",
    "VACUUM_REGION",
    "incident_direction",
    "refract_incident_direction",
    "simulate_trajectory",
    "sample_beam_reference",
    "compare_channel_information",
    "animate_trapezoidal_scan",
    "POINT_COLUMNS",
    "DEFAULT_INCIDENCE_ANGLES_DEG",
    "JMONSEL_ENERGIES_EV",
    "PlaneSamplerCase",
    "cosine_probability_grid",
    "generate_plane_sampler_library",
    "run_plane_sampler_case",
]

__version__ = "0.7.4"
